/*
 * This file is generated by jOOQ.
 */
package ru.mail.accounting.db.tables;


import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.mail.accounting.db.Keys;
import ru.mail.accounting.db.Public;
import ru.mail.accounting.db.tables.records.WaybillRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Waybill extends TableImpl<WaybillRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.waybill</code>
     */
    public static final Waybill WAYBILL = new Waybill();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WaybillRecord> getRecordType() {
        return WaybillRecord.class;
    }

    /**
     * The column <code>public.waybill.waybill_num</code>.
     */
    public final TableField<WaybillRecord, Integer> WAYBILL_NUM = createField(DSL.name("waybill_num"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.waybill.waybill_date</code>.
     */
    public final TableField<WaybillRecord, Date> WAYBILL_DATE = createField(DSL.name("waybill_date"), SQLDataType.DATE, this, "");

    /**
     * The column <code>public.waybill.org_sender</code>.
     */
    public final TableField<WaybillRecord, String> ORG_SENDER = createField(DSL.name("org_sender"), SQLDataType.VARCHAR(30).nullable(false), this, "");

    private Waybill(Name alias, Table<WaybillRecord> aliased) {
        this(alias, aliased, null);
    }

    private Waybill(Name alias, Table<WaybillRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.waybill</code> table reference
     */
    public Waybill(String alias) {
        this(DSL.name(alias), WAYBILL);
    }

    /**
     * Create an aliased <code>public.waybill</code> table reference
     */
    public Waybill(Name alias) {
        this(alias, WAYBILL);
    }

    /**
     * Create a <code>public.waybill</code> table reference
     */
    public Waybill() {
        this(DSL.name("waybill"), null);
    }

    public <O extends Record> Waybill(Table<O> child, ForeignKey<O, WaybillRecord> key) {
        super(child, key, WAYBILL);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Identity<WaybillRecord, Integer> getIdentity() {
        return (Identity<WaybillRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<WaybillRecord> getPrimaryKey() {
        return Keys.WAYBILL_NUM_PKEY;
    }

    @Override
    public List<UniqueKey<WaybillRecord>> getKeys() {
        return Arrays.<UniqueKey<WaybillRecord>>asList(Keys.WAYBILL_NUM_PKEY);
    }

    @Override
    public List<ForeignKey<WaybillRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<WaybillRecord, ?>>asList(Keys.WAYBILL__ORG_SENDER_FKEY);
    }

    public Organization organization() {
        return new Organization(this, Keys.WAYBILL__ORG_SENDER_FKEY);
    }

    @Override
    public Waybill as(String alias) {
        return new Waybill(DSL.name(alias), this);
    }

    @Override
    public Waybill as(Name alias) {
        return new Waybill(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Waybill rename(String name) {
        return new Waybill(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Waybill rename(Name name) {
        return new Waybill(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Date, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
