/*
 * This file is generated by jOOQ.
 */
package ru.mail.accounting.db;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import ru.mail.accounting.db.tables.FlywaySchemaHistory;
import ru.mail.accounting.db.tables.Nomenclature;
import ru.mail.accounting.db.tables.Organization;
import ru.mail.accounting.db.tables.Waybill;
import ru.mail.accounting.db.tables.WaybillPosition;
import ru.mail.accounting.db.tables.records.FlywaySchemaHistoryRecord;
import ru.mail.accounting.db.tables.records.NomenclatureRecord;
import ru.mail.accounting.db.tables.records.OrganizationRecord;
import ru.mail.accounting.db.tables.records.WaybillPositionRecord;
import ru.mail.accounting.db.tables.records.WaybillRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<NomenclatureRecord> ID_PKEY = Internal.createUniqueKey(Nomenclature.NOMENCLATURE, DSL.name("id_pkey"), new TableField[] { Nomenclature.NOMENCLATURE.ID }, true);
    public static final UniqueKey<OrganizationRecord> ORGNAME_PKEY = Internal.createUniqueKey(Organization.ORGANIZATION, DSL.name("orgName_pkey"), new TableField[] { Organization.ORGANIZATION.NAME }, true);
    public static final UniqueKey<WaybillRecord> WAYBILL_NUM_PKEY = Internal.createUniqueKey(Waybill.WAYBILL, DSL.name("waybill_num_pkey"), new TableField[] { Waybill.WAYBILL.WAYBILL_NUM }, true);
    public static final UniqueKey<WaybillPositionRecord> POSITION_PKEY = Internal.createUniqueKey(WaybillPosition.WAYBILL_POSITION, DSL.name("position_pkey"), new TableField[] { WaybillPosition.WAYBILL_POSITION.POSITION }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<WaybillRecord, OrganizationRecord> WAYBILL__ORG_SENDER_FKEY = Internal.createForeignKey(Waybill.WAYBILL, DSL.name("org_sender_fkey"), new TableField[] { Waybill.WAYBILL.ORG_SENDER }, Keys.ORGNAME_PKEY, new TableField[] { Organization.ORGANIZATION.NAME }, true);
    public static final ForeignKey<WaybillPositionRecord, NomenclatureRecord> WAYBILL_POSITION__NOMENCLATURE_FKEY = Internal.createForeignKey(WaybillPosition.WAYBILL_POSITION, DSL.name("nomenclature_fkey"), new TableField[] { WaybillPosition.WAYBILL_POSITION.NOMENCLATURE }, Keys.ID_PKEY, new TableField[] { Nomenclature.NOMENCLATURE.ID }, true);
    public static final ForeignKey<WaybillPositionRecord, WaybillRecord> WAYBILL_POSITION__WAYBILL_FKEY = Internal.createForeignKey(WaybillPosition.WAYBILL_POSITION, DSL.name("waybill_fkey"), new TableField[] { WaybillPosition.WAYBILL_POSITION.WAYBILL }, Keys.WAYBILL_NUM_PKEY, new TableField[] { Waybill.WAYBILL.WAYBILL_NUM }, true);
}
