/*
 * This file is generated by jOOQ.
 */
package ru.mail.accounting.db;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ru.mail.accounting.db.tables.FlywaySchemaHistory;
import ru.mail.accounting.db.tables.Nomenclature;
import ru.mail.accounting.db.tables.Organization;
import ru.mail.accounting.db.tables.Waybill;
import ru.mail.accounting.db.tables.WaybillPosition;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.nomenclature</code>.
     */
    public final Nomenclature NOMENCLATURE = Nomenclature.NOMENCLATURE;

    /**
     * The table <code>public.organization</code>.
     */
    public final Organization ORGANIZATION = Organization.ORGANIZATION;

    /**
     * The table <code>public.waybill</code>.
     */
    public final Waybill WAYBILL = Waybill.WAYBILL;

    /**
     * The table <code>public.waybill_position</code>.
     */
    public final WaybillPosition WAYBILL_POSITION = WaybillPosition.WAYBILL_POSITION;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.NOMENCLATURE_ID_SEQ,
            Sequences.WAYBILL_POSITION_POSITION_SEQ,
            Sequences.WAYBILL_WAYBILL_NUM_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Nomenclature.NOMENCLATURE,
            Organization.ORGANIZATION,
            Waybill.WAYBILL,
            WaybillPosition.WAYBILL_POSITION);
    }
}
