/*
 * This file is generated by jOOQ.
 */
package ru.mail.accounting.db;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.nomenclature_id_seq</code>
     */
    public static final Sequence<Integer> NOMENCLATURE_ID_SEQ = Internal.createSequence("nomenclature_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.waybill_position_position_seq</code>
     */
    public static final Sequence<Integer> WAYBILL_POSITION_POSITION_SEQ = Internal.createSequence("waybill_position_position_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.waybill_waybill_num_seq</code>
     */
    public static final Sequence<Integer> WAYBILL_WAYBILL_NUM_SEQ = Internal.createSequence("waybill_waybill_num_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);
}
