/*
 * This file is generated by jOOQ.
 */
package ru.mail.accounting.db;


import javax.annotation.Generated;

import ru.mail.accounting.db.tables.FlywaySchemaHistory;
import ru.mail.accounting.db.tables.Nomenclature;
import ru.mail.accounting.db.tables.Organization;
import ru.mail.accounting.db.tables.Waybill;
import ru.mail.accounting.db.tables.WaybillPosition;


/**
 * Convenience access to all tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.nomenclature</code>.
     */
    public static final Nomenclature NOMENCLATURE = Nomenclature.NOMENCLATURE;

    /**
     * The table <code>public.organization</code>.
     */
    public static final Organization ORGANIZATION = Organization.ORGANIZATION;

    /**
     * The table <code>public.waybill</code>.
     */
    public static final Waybill WAYBILL = Waybill.WAYBILL;

    /**
     * The table <code>public.waybill_position</code>.
     */
    public static final WaybillPosition WAYBILL_POSITION = WaybillPosition.WAYBILL_POSITION;
}
